Junit, timeout etc.
ASQ-USI/asq-java-q-backend pull request #7
Opened 2016-12-12 22:10 UTC by Rebinskiy

Added junit library, timeout and some functionality to client.js

Is it maybe better to create a docker image with junit already inside and use that one?

Needs speed optimisation and stress testing.

2016-12-13 07:07 UTC, VincenzoFerme commented
@Rebinskiy can you explain me how do you do it now, and what is the difference compared to the workflow you follow when you do not have dependencies of you code for third-party libraries?

2016-12-13 14:35 UTC, Rebinskiy commented
@VincenzoFerme now I just pass a locally stored library to container.putArchive() when initialising a container that need to use the library, the idea is that the client should give information about needed libraries, by default now is junit only

2016-12-13 14:35 UTC, VincenzoFerme commented
@StKyr please upload here the image and the details out of you discussion. @Rebinskiy discuss with @StKyr about how to approach the problem. Moreover you should also discuss with @triglian about how to pipe directly the input from the user to the Docker copy command.

2016-12-13 15:54 UTC, VincenzoFerme commented
Great you decided to give it a try. In case of any issue ping me on this pull request.

2016-12-14 18:59 UTC, VincenzoFerme requested changes

2016-12-14 18:59 UTC, VincenzoFerme commented on app.js
> +function runJava_2(clientId, main, files, timeLimitCompile, timeLimitExecution) {
Change the name to a more meaningful one.

2016-12-14 19:01 UTC, VincenzoFerme requested changes

2016-12-14 19:01 UTC, VincenzoFerme commented on client.js
> +            compileTimeoutMs : 1000000,
Why exactly 16 mins and 40 seconds?

2016-12-15 15:58 UTC, VincenzoFerme commented on javaBox.js
> +            exec.start((err, stream) => {
You should be able to obtain the complete log from the container at the end of its execution, before deleting it. But this solution is fine as well.

2016-12-15 18:23 UTC, VincenzoFerme approved these changes

2016-12-15 18:41 UTC, merged